language: smalltalk
sudo: false

before-install: 
  - echo "before install"

# Download sources
before-script: 
  - echo "before script"
  - ./loadSources.sh

# Select operating system(s)
os:
  - linux
  - osx

# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo-alpha
  - Pharo-stable
  - Pharo-5.0
