language: smalltalk
sudo: false

# Download sources
before_script: 
  - ./.utilities/loadSources.sh

# Select operating system(s)
os:
  - linux
# JK: smalltalk sources cannot be accessed on MAC, dunno why 
#  - osx

# Select compatible Smalltalk image(s)
smalltalk:
#  - Pharo-alpha
  - Pharo-stable
  - Pharo-5.0
